name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs the workflow every 6 hours
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake gif and svg using Platane's snk action
      - name: Generate Snake GIF and SVG
        uses: Platane/snk@master
        with:
          github_user_name: HARSHSINGH3118
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the generated snake to the output branch
      - name: Push snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Ensure you have an "output" branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Print confirmation that the snake was generated
      - name: Confirm Snake Generation
        run: echo "Snake generation completed and pushed to output branch."
